site_name: Gravity Layer Documentation
nav:
    - Getting Started: index.md
    - Unity 3D SDK: 
        - Introduction: unitySDK.md
        - Installation: installation.md
        - Usage Example: examples.md
    - Unreal Engine 5.0 Plugin:
        - Introduction: UnrealEngine5Plugin.md
        - Integration: UnrealEngine5Integration.md
        - Example: UnrealEngine5Integration.md
        - Download: UnrealEngine5Download.md
        - Troubleshoot: UnrealEngine5Troubleshoot.md
theme:
    name: 'material'
    logo: 'assets/gravity-logo-light.svg'
    icon:
      admonition:
          note: octicons/tag-16
          abstract: octicons/checklist-16
          info: octicons/info-16
          tip: octicons/squirrel-16
          success: octicons/check-16
          question: octicons/question-16
          warning: octicons/alert-16
          failure: octicons/x-circle-16
          danger: octicons/zap-16
          bug: octicons/bug-16
          example: octicons/beaker-16
          quote: octicons/quote-16
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences