site_name: Gravity Layer Unreal Plugin
nav:
    - Getting Started: index.md
    - Unity 3D SDK: 
        - Introduction: unitySDK.md
        - Installation: installation.md
        - Usage Example: examples.md
    - Unreal Engine 5.0 Plugin:
        - Introduction: UnrealEngine5Plugin.md
    - Unreal Engine / Introduction: UnrealEngine5Plugin.md
theme: material
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html